### ISSUE TITLE
URLRewrite support

### ISSUE THREAD

**Issue by manobi** [hashicorp/consul-api-gateway#233]
### Is your feature request related to a problem? Please describe.
HTTPRoute URLRewrite filter support is a deal breaker for the company I work for.
I have tried to use it following [Gateway API spec](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1alpha2.HTTPURLRewriteFilter), but had no success.

The [supported features doc](https://github.com/hashicorp/consul-api-gateway/blob/main/dev/docs/supported-features.md) does not confirm support as well.

Is it actually supported or planned?

### Use Case(s)
**Given** that "/orders" redirect to order service
**When** I reach "/orders/10"
**Then** orders service request path must be "/10"
**And** request path should not have "/orders" prefix

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: orders
  namespace: consul
spec:
  parentRefs:
  - name: api-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /orders
      backendRefs:
        - kind: Service
          name: orders
          namespace: orders
          port: 80
          weight: 100
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: replacePrefixMatch
              value: /orders
```
