### ISSUE TITLE
API Gateway pods fail to start if namespace mirroring enabled and destination namespace doesn't exist

### ISSUE THREAD

**Issue by krarey** [hashicorp/consul-api-gateway#248]
### Overview of the Issue

When the Connect Injector job has been deployed in namespace-mirroring mode, new API Gateway pods get stuck in a crash loop during initial auth/token exchange if the matching namespace of the underlying kube Gateway resource has not already been created in Consul. 

### Reproduction Steps
1. Deploy API Gateway CRDs
2. Deploy Consul Enterprise via Helm with API gateway, ACLs, and namespace mirroring enabled
3. Deploy a new `gateway.networking.k8s.io/v1alpha2 Gateway` resource in a non-default kube namespace

### Logs

```
{"@caller":"/home/runner/work/consul-api-gateway/consul-api-gateway/internal/consul/auth.go:55","@level":"error","@message":"error authenticating","@module":"consul-api-gateway-exec.authenticator","@timestamp":"2022-06-27T22:19:07.025849Z","error":"Unexpected response code: 500 (rpc error making call: rpc error making call: Namespace \"consul\" does not exist in Partition \"default\")"}
```

### Expected behavior

Following the same pattern established by the connect-inject process, I would expect consul-api-gateway-controller or an init container to check for the existence of the destination Consul namespace, and create one if it doesn't exist.

### Environment details

- consul-api-gateway version: 0.3.0
- Kubernetes version: v1.22.8-gke.202
- Consul Server version: v1.12.2-ent
- Consul-K8s version: v0.45.0
- Cloud Provider: GCP GKE

Helm values:
```
global:
  enabled: true
  name: consul
  domain: consul
  peering:
    enabled: true
  adminPartitions:
    enabled: true
    name: "default"
  image: "hashicorp/consul-enterprise:1.12.2-ent"
  imageK8S: "hashicorp/consul-k8s-control-plane:0.45.0"
  datacenter: gke
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    enableAutoEncrypt: false
  enableConsulNamespaces: true
  acls:
    manageSystemACLs: true
    createReplicationToken: true
  enterpriseLicense:
    secretName: consul-license
    secretKey: key
    enableLicenseAutoload: true
  imageEnvoy: "envoyproxy/envoy:v1.22.2"
server:
  enabled: true
  replicas: 3
  storage: 10Gi
  storageClass: premium-rwo
  connect: true
  updatePartition: 0
client:
  enabled: true
dns:
  enabled: true
ui:
  enabled: true
connectInject:
  enabled: true
  transparentProxy:
    defaultEnabled: false
  consulNamespaces:
    mirroringK8S: true
controller:
  enabled: true
meshGateway:
  enabled: true
  replicas: 2
  service:
    enabled: true
    type: LoadBalancer
    port: 443
apiGateway:
  enabled: true
  image: "hashicorp/consul-api-gateway:0.3.0"
  managedGatewayClass:
    enabled: true
  controller:
    replicas: 1
```
