### ISSUE TITLE
API Gateway doesn't attach cross-namespace lookup policy on namespace creation

### ISSUE THREAD

**Issue by krarey** [hashicorp/consul-api-gateway#510]
### Overview of the Issue

This issue impacts API Gateway instances created in Kubernetes, with Consul Enterprise clusters leveraging namespace mirroring.

When an API Gateway instance is launched in a Kubernetes namespace whose equivalent does not yet exist in Consul, it creates a matching namespace automatically. This mimics the behavior of consul connect-inject in the same scenario.

The created namespace needs a default policy assigned permitting cross-namespace service lookup, which is currently skipped by API Gateway Controller. Without this policy, the ACL token given to the API Gateway pods cannot discover the appropriate endpoints for any target services that are not in the same namespace as the gateway.

### Reproduction Steps

* Deploy Consul Enterprise to a kubernetes cluster with the following features enabled:
```yaml
global:
  image: "hashicorp/consul-enterprise:1.14.3-ent"
  enableConsulNamespaces: true
  acls:
    manageSystemACLs: true
connectInject:
  enabled: true
  consulNamespaces:
    mirroringK8S: true
apiGateway:
  enabled: true
  image: hashicorp/consul-api-gateway:0.5.1
  imageEnvoy: envoyproxy/envoy:v1.23.1
```

* Create a new kubernetes namespace, and deploy a Gateway resource to that namespace:
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: apigw
  namespace: apigateway
spec:
  gatewayClassName: consul-api-gateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
```

* Create a different kubernetes namespace, and deploy a reference connect-injected application and service:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
  namespace: demoapp
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: demoapp
spec:
  selector:
    app: dashboard
  ports:
  - port: 9002
    targetPort: 9002
    name: dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashboard
  name: dashboard
  namespace: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'counting:9001'
      labels:
        app: dashboard
    spec:
      serviceAccountName: dashboard
      containers:
      - name: dashboard
        image: hashicorp/dashboard-service:0.0.4
        ports:
        - containerPort: 9002
        env:
        - name: COUNTING_SERVICE_URL
          value: 'http://127.0.0.1:9001'
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: dashboard
  namespace: demoapp
spec:
  protocol: http
```

* Define an HTTPRoute/TCPRoute linking the API Gateway and target service:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: dashboard
  namespace: demoapp
spec:
  parentRefs:
    - name: apigw
      namespace: apigateway
  rules:
    - backendRefs:
      - kind: Service
        name: dashboard
        namespace: demoapp
        port: 9002
```

* The API Gateway will accept the route, and the backing ingress-gateway config entry will be updated to appropriately reference the target service. However, inspecting the envoy clusters endpoint for an individual API Gateway instance will show no known upstreams.

* Updating the newly-created namespace with the `cross-namespace-policy` automatically created by consul-k8s at cluster initialization will allow the API gateway's token to begin discovering service endpoints in other namespaces: `consul namespace update -name=apigateway -default-policy-name=cross-namespace-policy` (Note, this must be done via CLI or the HTTP API. The Consul UI seems to have a bug associating a new default policy to an existing namespace created in this manner. Perhaps due to the `external-source` meta applied to the namespace?)

### Expected behavior

API Gateway Controller should apply `cross-namespace-policy` to any created namespaces automatically, when ACLs and Namespaces are in use.
