### ISSUE TITLE
“rules.matches.method” only accepts single entry (string)

### ISSUE THREAD

**Issue by kds-rune** [hashicorp/consul-api-gateway#581]
### Overview of the Issue

Unable to add more than 1 entry in the "rules.matches.method”
Documentation states this should be provided as list, but only accepts a string.

See related [Discuss](https://discuss.hashicorp.com/t/consul-api-gateway-rules-matches-method/54254)

### Reproduction Steps

1. Deploy API Gateway. The following example HTTPRoute configuration only works for 1 x "method" (replace ns/svc as needed):

<details>

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: default
spec:
  hostnames: []
  parentRefs:
  - name: api-gateway
  rules:
  - matches:
    - method: HEAD
      path:
        type: PathPrefix
        value: /whoareyou
      headers:
      - name: Host
        type: RegularExpression
        value: "^localhost:.+$"
    backendRefs:
    - kind: Service
      name: whoami
      namespace: default
      port: 80
      weight: 100
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /whoami
```
</details>

### Logs

kubectl output

<details>

```bash
The HTTPRoute "whoami" is invalid: 
* spec.rules[1].matches[0].method: Invalid value: "array": spec.rules[1].matches[0].method in body must be of type string: "array"
* spec.rules[1].matches[0].method: Unsupported value: []interface {}{"HEAD", "GET"}: supported values: "GET", "HEAD", "POST", "PUT", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH"
```

</details>

### Expected behavior

Able to add more than 1 method, as stated in [documentation](https://developer.hashicorp.com/consul/docs/api-gateway/configuration/routes#rules-matches-method)

### Environment details

- `consul-api-gateway` version: 0.5.4
- `Kubernetes` version: v1.25.9 (docker desktop, Windows)
- `Consul Server` version: v1.15.2
- Deployment: Helm Chart v1.1.1 (Kustomized)
- Cloud Provider: Docker desktop (Windows 11/wsl2)

### Additional Context

N/A

**Comment by mikemorris** [comment]
The way to configure the behavior you're describing would be to add multiple match clauses, as mentioned in https://developer.hashicorp.com/consul/docs/api-gateway/configuration/routes#rules-matches (the mention of a list in the docs you linked is inaccurate and should be updated).

Multiple matches are combined as any/OR, but within a single match, parameters are ANDed together. This is described in a bit more detail in the upstream Gateway API documentation:
- [HTTPRouteRule](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteRule)
- [HTTPRouteMatch](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteMatch)

Could you try applying the configuration below to see if it solves your use case?
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: default
spec:
  hostnames: []
  parentRefs:
  - name: api-gateway
  rules:
  - matches:
    - method: HEAD
      path:
        type: PathPrefix
        value: /whoareyou
      headers:
      - name: Host
        type: RegularExpression
        value: "^localhost:.+$"
    - method: GET
      path:
        type: PathPrefix
        value: /whoareyou
      headers:
      - name: Host
        type: RegularExpression
        value: "^localhost:.+$"
    backendRefs:
    - kind: Service
      name: whoami
      namespace: default
      port: 80
      weight: 100
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /whoami
```

This is admittedly a bit verbose, so you may want to consider some templating layer for generating this more concisely, as well as opening an issue upstream in https://github.com/kubernetes-sigs/gateway-api describing your use case and suggesting adding support for a `methods` array field on [`HTTPRouteMatch`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRouteMatch).
